### PR TITLE
Easier settings merge pull request

### PR DESCRIPTION
**Pull request by Oakchris1955**
So, there are still some thing left to do. The most important one is German locale by @moritz-t-w. The other one is Moritz's opinion about the pull request

### CODE REVIEW

**Comment by Oakchris1955** [comment]
I am happy to announce that I have met 3 of the 4 goals from commit ef15a29f8485b00bd7269278b7d5b9ab347f577c

These are:
1) Configure other locales (except German, but whatever)
2) Check why question mark is ignored
3) More info on the help command output

The one goal I didn't meet was remove commented code, which I will do soon. Also, right now, I am introducing the `change` command

**Review by moritztim — APPROVED** [review]

**Comment by Oakchris1955** [comment]
Don't mind the force push, commited some code that shouldn't have been commited by accident

**Review by moritztim — CHANGES_REQUESTED** [review]
Use less words to describe the commands. Things like "A simple command to" are unnecesairy, while others like "without raising an error" don't concern the user, the user wouldn't have expected it to raise an error, so don't mention it.

**Review by moritztim — APPROVED** [review]

**Comment by Oakchris1955** [comment]
Time to merge!!!

**Pull request merged**
